#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/zfarouk/.local/code/usr/share/code/code" "/home/zfarouk/Desktop/warbiiiii/~/goinfre/code/config/Code/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "" "$@"